# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-08-07 00:37:28
"""
import arcpy

def Model3():  # Model3

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    #input from step1
    new_stops = "new stops"

    # Process: Density-based Clustering (Density-based Clustering) (stats)
    dbscan_step1_shp = "C:\\Users\\anranzheng\\Dropbox (UFL)\\Mobility Hub\\Anran\\module builder\\process\\dbscan_step1.shp"
    arcpy.stats.DensityBasedClustering(in_features=new_stops, output_features=dbscan_step1_shp, cluster_method="DBSCAN", min_features_cluster=2, search_distance="100 Meters", cluster_sensitivity=None, time_field="", search_time_interval="")

    # Process: Select Layer By Attribute (2) (Select Layer By Attribute) (management)
    dbscan_step1_Layer1, Count_2_ = arcpy.management.SelectLayerByAttribute(in_layer_or_view=dbscan_step1_shp, selection_type="NEW_SELECTION", where_clause="CLUSTER_ID <> -1", invert_where_clause="")

    # Process: Dissolve (Dissolve) (management)
    test_shp = "C:\\Users\\anranzheng\\Dropbox (UFL)\\Mobility Hub\\Anran\\module builder\\process\\test.shp"
    arcpy.management.Dissolve(in_features=dbscan_step1_Layer1, out_feature_class=test_shp, dissolve_field=["CLUSTER_ID"], statistics_fields=[], multi_part="MULTI_PART", unsplit_lines="DISSOLVE_LINES", concatenation_separator="")

    # Process: Buffer (2) (Buffer) (analysis)
    grouped_buffer_shp = "C:\\Users\\anranzheng\\Dropbox (UFL)\\Mobility Hub\\Anran\\module builder\\process\\grouped_buffer.shp"
    arcpy.analysis.Buffer(in_features=test_shp, out_feature_class=grouped_buffer_shp, buffer_distance_or_field="1600 Meters", line_side="FULL", line_end_type="ROUND", dissolve_option="NONE", dissolve_field=[], method="PLANAR")

    # Process: Select Layer By Attribute (Select Layer By Attribute) (management)
    dbscan_step1_Layer, Count = arcpy.management.SelectLayerByAttribute(in_layer_or_view=dbscan_step1_shp, selection_type="NEW_SELECTION", where_clause="CLUSTER_ID = -1", invert_where_clause="")

    # Process: Copy Features (Copy Features) (management)
    test2_shp = "C:\\Users\\anranzheng\\Dropbox (UFL)\\Mobility Hub\\Anran\\module builder\\process\\test2.shp"
    arcpy.management.CopyFeatures(in_features=dbscan_step1_Layer, out_feature_class=test2_shp, config_keyword="", spatial_grid_1=None, spatial_grid_2=None, spatial_grid_3=None)

    # Process: Buffer (Buffer) (analysis)
    noise100_shp = "C:\\Users\\anranzheng\\Dropbox (UFL)\\Mobility Hub\\Anran\\module builder\\process\\noise100.shp"
    arcpy.analysis.Buffer(in_features=test2_shp, out_feature_class=noise100_shp, buffer_distance_or_field="1.6 Kilometers", line_side="FULL", line_end_type="ROUND", dissolve_option="NONE", dissolve_field=[], method="PLANAR")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\anranzheng\OneDrive - University of Florida\Documents\ArcGIS\Projects\gnv mobility hub\gnv mobility hub.gdb", workspace=r"C:\Users\anranzheng\OneDrive - University of Florida\Documents\ArcGIS\Projects\gnv mobility hub\gnv mobility hub.gdb"):
        Model3()
