# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-08-08 01:14:31
"""
import arcpy
from sys import argv
def #  NOT  IMPLEMENTED# Function Body not implemented

def Model5(gnv_census="gnv_census"):  # Model5

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    result2 = "result2"

    for I_result461_index, Value in #  NOT  IMPLEMENTED(result2, [["index", ""]], True):

        # Process: Intersect (Intersect) (analysis)
        Value = "628"
        test_Intersect_Value_ = fr"C:\Users\anranzheng\OneDrive - University of Florida\Documents\ArcGIS\Projects\gnv mobility hub\gnv mobility hub.gdb\test_Intersect{Value}"
        arcpy.analysis.Intersect(in_features=[[gnv_census, ""], [I_result461_index, ""]], out_feature_class=test_Intersect_Value_, join_attributes="ALL", cluster_tolerance="", output_type="INPUT")

        # Process: Copy Features (Copy Features) (management)
        socio_Value_shp = fr"C:\Users\anranzheng\Dropbox (UFL)\Mobility Hub\Anran\module builder\process\socio\socio_{Value}.shp"
        arcpy.management.CopyFeatures(in_features=test_Intersect_Value_, out_feature_class=socio_Value_shp, config_keyword="", spatial_grid_1=None, spatial_grid_2=None, spatial_grid_3=None)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\anranzheng\OneDrive - University of Florida\Documents\ArcGIS\Projects\gnv mobility hub\gnv mobility hub.gdb", workspace=r"C:\Users\anranzheng\OneDrive - University of Florida\Documents\ArcGIS\Projects\gnv mobility hub\gnv mobility hub.gdb"):
        Model5(*argv[1:])
